// ===== MULTI-LANGUAGE SUPPORT =====
const languages = {
    en: {
        home: 'Home',
        verify: 'Verify',
        about: 'About',
        heroTitle: 'Verify Internship Certificates',
        heroSubtitle: 'Secure and instant verification of your internship certificates',
        verifyNow: 'Verify Now',
        learnMore: 'Learn More',
        certificateVerification: 'Certificate Verification',
        enterId: 'Enter Certificate ID',
        enterIdPlaceholder: 'Enter Certificate ID (e.g., INT-2024-001)',
        verifyBtn: 'Verify',
        or: 'OR',
        scanQR: 'Scan QR Code',
        openScanner: '📷 Open Scanner',
        aboutSystem: 'About This System',
        aboutText: 'Our internship certificate verification system provides a secure and efficient way to verify the authenticity of internship certificates.',
        secure: '🔒 Secure',
        secureText: 'Blockchain-inspired verification system',
        fast: '⚡ Fast',
        fastText: 'Instant verification results',
        qrCode: '📱 QR Code',
        qrText: 'Scan to verify instantly',
        verified: '✅ Verified',
        invalid: '❌ Invalid',
        certificateId: 'Certificate ID:',
        internship: 'Internship:',
        duration: 'Duration:',
        completionDate: 'Completion Date:',
        viewCertificate: '📄 View Full Certificate',
        downloadCertificate: '⬇️ Download Certificate',
        printCertificate: '🖨️ Print Certificate',
        share: 'Share Your Verified Certificate',
        footer: '© 2024 InternVerify. All rights reserved.',
        searchByName: '🔍 Search by Name',
        searchPlaceholder: 'Search by student name...',
        searchBtn: '🔍 Search',
        clearBtn: 'Clear',
        noResults: 'No certificates found for',
        foundResults: 'Found {count} certificate(s) for',
        searchPrompt: 'Please enter a name to search.',
        noCertificate: 'No certificate to download. Please verify first.',
        downloadStarted: '📥 Downloading your original certificate...',
        adminLogin: '🔐 Admin Login',
        username: 'Username',
        password: 'Password',
        login: 'Login',
        logout: 'Logout',
        dashboard: 'Dashboard'
    },
    hi: {
        home: 'होम',
        verify: 'सत्यापन',
        about: 'हमारे बारे में',
        heroTitle: 'इंटर्नशिप प्रमाणपत्र सत्यापित करें',
        heroSubtitle: 'अपने इंटर्नशिप प्रमाणपत्रों का सुरक्षित और त्वरित सत्यापन',
        verifyNow: 'अभी सत्यापित करें',
        learnMore: 'और जानें',
        certificateVerification: 'प्रमाणपत्र सत्यापन',
        enterId: 'प्रमाणपत्र आईडी दर्ज करें',
        enterIdPlaceholder: 'प्रमाणपत्र आईडी दर्ज करें (जैसे, INT-2024-001)',
        verifyBtn: 'सत्यापित करें',
        or: 'या',
        scanQR: 'क्यूआर कोड स्कैन करें',
        openScanner: '📷 स्कैनर खोलें',
        aboutSystem: 'इस प्रणाली के बारे में',
        aboutText: 'हमारी इंटर्नशिप प्रमाणपत्र सत्यापन प्रणाली प्रमाणपत्रों की प्रामाणिकता को सत्यापित करने का एक सुरक्षित और कुशल तरीका प्रदान करती है।',
        secure: '🔒 सुरक्षित',
        secureText: 'ब्लॉकचेन-प्रेरित सत्यापन प्रणाली',
        fast: '⚡ तेज़',
        fastText: 'त्वरित सत्यापन परिणाम',
        qrCode: '📱 क्यूआर कोड',
        qrText: 'तुरंत सत्यापित करने के लिए स्कैन करें',
        verified: '✅ सत्यापित',
        invalid: '❌ अमान्य',
        certificateId: 'प्रमाणपत्र आईडी:',
        internship: 'इंटर्नशिप:',
        duration: 'अवधि:',
        completionDate: 'पूर्णता तिथि:',
        viewCertificate: '📄 पूरा प्रमाणपत्र देखें',
        downloadCertificate: '⬇️ प्रमाणपत्र डाउनलोड करें',
        printCertificate: '🖨️ प्रमाणपत्र प्रिंट करें',
        share: 'अपना सत्यापित प्रमाणपत्र साझा करें',
        footer: '© 2024 इंटर्नवेरीफाई। सर्वाधिकार सुरक्षित।',
        searchByName: '🔍 नाम से खोजें',
        searchPlaceholder: 'छात्र के नाम से खोजें...',
        searchBtn: '🔍 खोजें',
        clearBtn: 'साफ़ करें',
        noResults: 'के लिए कोई प्रमाणपत्र नहीं मिला',
        foundResults: '{count} प्रमाणपत्र मिले',
        searchPrompt: 'कृपया खोजने के लिए एक नाम दर्ज करें।',
        noCertificate: 'डाउनलोड करने के लिए कोई प्रमाणपत्र नहीं। कृपया पहले सत्यापित करें।',
        downloadStarted: '📥 आपका मूल प्रमाणपत्र डाउनलोड हो रहा है...',
        adminLogin: '🔐 व्यवस्थापक लॉगिन',
        username: 'उपयोगकर्ता नाम',
        password: 'पासवर्ड',
        login: 'लॉगिन',
        logout: 'लॉगआउट',
        dashboard: 'डैशबोर्ड'
    },
    bn: {
        home: 'হোম',
        verify: 'ভেরিফাই',
        about: 'সম্পর্কে',
        heroTitle: 'ইন্টার্নশিপ সার্টিফিকেট ভেরিফাই করুন',
        heroSubtitle: 'আপনার ইন্টার্নশিপ সার্টিফিকেটের নিরাপদ এবং তাৎক্ষণিক ভেরিফিকেশন',
        verifyNow: 'এখনই ভেরিফাই করুন',
        learnMore: 'আরও জানুন',
        certificateVerification: 'সার্টিফিকেট ভেরিফিকেশন',
        enterId: 'সার্টিফিকেট আইডি লিখুন',
        enterIdPlaceholder: 'সার্টিফিকেট আইডি লিখুন (যেমন, INT-2024-001)',
        verifyBtn: 'ভেরিফাই',
        or: 'অথবা',
        scanQR: 'কিউআর কোড স্ক্যান করুন',
        openScanner: '📷 স্ক্যানার খুলুন',
        aboutSystem: 'এই সিস্টেম সম্পর্কে',
        aboutText: 'আমাদের ইন্টার্নশিপ সার্টিফিকেট ভেরিফিকেশন সিস্টেম সার্টিফিকেটের সত্যতা যাচাই করার একটি নিরাপদ এবং দক্ষ উপায় প্রদান করে।',
        secure: '🔒 নিরাপদ',
        secureText: 'ব্লকচেইন-অনুপ্রাণিত ভেরিফিকেশন সিস্টেম',
        fast: '⚡ দ্রুত',
        fastText: 'তাৎক্ষণিক ভেরিফিকেশন ফলাফল',
        qrCode: '📱 কিউআর কোড',
        qrText: 'তাৎক্ষণিকভাবে ভেরিফাই করতে স্ক্যান করুন',
        verified: '✅ ভেরিফাইড',
        invalid: '❌ অবৈধ',
        certificateId: 'সার্টিফিকেট আইডি:',
        internship: 'ইন্টার্নশিপ:',
        duration: 'মেয়াদ:',
        completionDate: 'সমাপ্তির তারিখ:',
        viewCertificate: '📄 সম্পূর্ণ সার্টিফিকেট দেখুন',
        downloadCertificate: '⬇️ সার্টিফিকেট ডাউনলোড করুন',
        printCertificate: '🖨️ সার্টিফিকেট প্রিন্ট করুন',
        share: 'আপনার ভেরিফাইড সার্টিফিকেট শেয়ার করুন',
        footer: '© ২০২৪ ইন্টার্নভেরিফাই। সর্বস্বত্ব সংরক্ষিত।',
        searchByName: '🔍 নাম দিয়ে খুঁজুন',
        searchPlaceholder: 'শিক্ষার্থীর নাম দিয়ে খুঁজুন...',
        searchBtn: '🔍 খুঁজুন',
        clearBtn: 'সাফ করুন',
        noResults: 'এর জন্য কোনো সার্টিফিকেট পাওয়া যায়নি',
        foundResults: '{count}টি সার্টিফিকেট পাওয়া গেছে',
        searchPrompt: 'অনুগ্রহ করে খোঁজার জন্য একটি নাম লিখুন।',
        noCertificate: 'ডাউনলোড করার জন্য কোনো সার্টিফিকেট নেই। দয়া করে প্রথমে ভেরিফাই করুন।',
        downloadStarted: '📥 আপনার মূল সার্টিফিকেট ডাউনলোড হচ্ছে...',
        adminLogin: '🔐 অ্যাডমিন লগইন',
        username: 'ইউজারনেম',
        password: 'পাসওয়ার্ড',
        login: 'লগইন',
        logout: 'লগআউট',
        dashboard: 'ড্যাশবোর্ড'
    }
};